### PR TITLE
Discord link style in sidebar

### PR DESCRIPTION
**Pull request by markspolakovs**

### CODE REVIEW

**Comment by markspolakovs** [comment]
bootiful

bootiful

**Comment by Foxgott16** [comment]
Maybe add the Facebook, Twitter and Discord logos. 



_So it's [LOGO] @VLive.., [FB LOGO] /VLive..   [DIS.LOGO]Discord_

**Comment by markspolakovs** [comment]
@Foxgott16 Good idea, but I'd like to do that in a separate PR.

**Review by Foxgott16 — APPROVED** [review]
Phuh - found the approve button, mate. Don't worry. Took just a few minutes.

**Review by Foxgott16 — APPROVED** [review]

**Review by Foxgott16 — APPROVED** [review]
This confuses me.

**Pull request merged**
